# Generated by Django 5.2.8 on 2025-12-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=35, verbose_name='Пароль')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('email', models.EmailField(max_length=254, verbose_name='Адрес электронной почты')),
                ('regday', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
        ),
    ]
